"""add user_id to videos

Revision ID: 00865def2cf1
Revises: 4de37d498bf1
Create Date: 2023-11-06 16:51:29.976074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00865def2cf1'
down_revision = '4de37d498bf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True, foreign_keys='users.id'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
