"""new fields in videos

Revision ID: 4de37d498bf1
Revises: d5258e72e429
Create Date: 2023-11-06 15:31:41.549424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4de37d498bf1'
down_revision = 'd5258e72e429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('interpret', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('videos', schema=None) as batch_op:
        batch_op.drop_column('interpret')

    # ### end Alembic commands ###
